#!/bin/bash -ex

[[ -z "$FAB_HTTP_PROXY" ]] || export http_proxy=$FAB_HTTP_PROXY
[[ -z "$FAB_HTTPS_PROXY" ]] || export https_proxy=$FAB_HTTPS_PROXY

git clone --depth 1 --branch 5.0 https://github.com/bugzilla/bugzilla.git /var/www/bugzilla
