#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

URL=http://ftp.mozilla.org/pub/mozilla.org/webtools/bugzilla-4.4.tar.gz
dl $URL /usr/local/src

