#!/bin/bash -ex

DB_NAME=bugzilla
DB_USER=bugzilla
DB_PASS=$(mcookie)

ADMIN_MAIL=admin@example.com
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/bugzilla

# set ownership
chown -R www-data:www-data $WEBROOT

# configure apache
a2dissite 000-default
a2ensite bugzilla
a2enmod rewrite
a2enmod headers
a2enmod expires
a2enmod cgid

# setup the database
/etc/init.d/mysql start
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME --default-character-set=utf8;
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# configure bugzilla
cat > $WEBROOT/answers <<EOF
\$answer{'create_htaccess'} = 1;
\$answer{'webservergroup'} = 'www-data';
\$answer{'use_suexec'} = 0;
\$answer{'index_html'} = 0;
\$answer{'cvs_bin'} = '';
\$answer{'interdiffbin'} = '';
\$answer{'diffpath'} = '/usr/bin';
\$answer{'site_wide_secret'} = '$(mcookie)$(mcookie)';
\$answer{'db_host'} = 'localhost';
\$answer{'db_driver'} = 'mysql';
\$answer{'db_name'} = '$DB_NAME';
\$answer{'db_user'} = '$DB_USER';
\$answer{'db_pass'} = '$DB_PASS';
\$answer{'db_sock'} = '';
\$answer{'db_port'} = 0;
\$answer{'db_check'} = 0;
\$answer{'urlbase'} = '/';
\$answer{'ADMIN_EMAIL'} = '$ADMIN_MAIL';
\$answer{'ADMIN_PASSWORD'} = '$ADMIN_PASS';
\$answer{'ADMIN_REALNAME'} = 'admin';
\$answer{'SMTP_SERVER'} = 'localhost';
\$answer{'NO_PAUSE'} = 1
EOF

cd $WEBROOT

echo -e 'y\nq\n' | cpan
echo -e 'y\n' | cpan install Email::Reply Daemon::Generic PatchReader Email::Reply XMLRPC::Lite File::Copy::Recursive File::Which

# note checksetup.pl creates appropriate .htaccess files (if they don't already exist; unless $create_htaccess = 0)
./checksetup.pl $WEBROOT/answers
echo 'admin\n' | ./checksetup.pl $WEBROOT/answers
rm $WEBROOT/answers

# run collectstats - scripts so stats page doesn't error
./collectstats.pl

/etc/init.d/mysql stop

# cron jobs
echo "
0 0 * * * (cd $WEBROOT && ./collectstats.pl)
0 0 * * * (cd $WEBROOT && ./whineatnews.pl)
0,15,30,45 * * * * (cd $WEBROOT && ./whine.pl)
" | crontab -u root -

rm -rf /root/.cpan
apt-get purge -y gcc make
apt-get autoremove -y
