#!/bin/bash -e
# regenerate bugzilla mysql password and secret

. /etc/default/inithooks

PASSWORD=$(mcookie)
SECRET=$(mcookie)$(mcookie)
CONF=/var/www/bugzilla/localconfig

sed -i "s|db_pass.*|db_pass = \'$PASSWORD\';|" $CONF
sed -i "s|site_wide_secret.*|site_wide_secret = \'$SECRET\';|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=bugzilla --pass="$PASSWORD"
