#!/bin/bash -e
# regenerate bugzilla mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/bugzilla3/localconfig
sed -i "s/\$db_pass = \(.*\)/\$db_pass = \'$PASSWORD\';/" $CONF

CONF=/etc/dbconfig-common/bugzilla3.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=bugzilla3 --pass="$PASSWORD"
