#!/bin/bash -e
# set bugzilla admin email, password and outgoing email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

if [ -z "$APP_OUTMAIL" ]; then
    if [ -n "$APP_PASS" ] && [ -n "$APP_EMAIL" ]; then
        APP_OUTMAIL="DEFAULT"
    fi
fi

$INITHOOKS_PATH/bin/bugzilla.py --pass="$APP_PASS" --email="$APP_EMAIL" --outmail="$APP_OUTMAIL"

